repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: check-json
    - id: check-yaml
    - id: check-symlinks
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "v3.0.0-alpha.9-for-vscode"
  hooks:
    - id: prettier
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: "v8.41.0"
  hooks:
    - id: eslint
      files: \.ts$
- repo: https://github.com/awebdeveloper/pre-commit-stylelint
  rev: "0.0.2"
  hooks:
    - id: stylelint
