repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.41.0"
    hooks:
      - id: eslint
        additional_dependencies:
        - typescript-eslint
        files: \.[jt]sx?$
        types: [file]
  - repo: https://github.com/thlorenz/doctoc
    rev: "v2.2.0"
    hooks:
      - id: doctoc
